- name: Init Docker Swarm Mode On First Manager
  command: docker swarm init --advertise-addr {{ansible_default_ipv4.address}}
  when: '"Swarm: inactive" in docker_info.stdout'
- name: Capture Docker Swarm Worker join-token
  command: "docker swarm join-token -q worker"
  changed_when: false
  register: "worker_token_output"
- name: Define Docker Swarm Worker join-token
  set_fact:
    worker_token: "{{ worker_token_output.stdout }}"
  changed_when: false
- name: Capture Docker Swarm Manager join-token
  command: "docker swarm join-token -q manager"
  changed_when: false
  register: "manager_token_output"
- name: Define Docker Swarm Manager join-token
  set_fact:
    manager_token: "{{ manager_token_output.stdout }}"
  changed_when: false
