---
  - name: Setup Docker Swarm Primary Manager
    include: register-primary-manager.yml
    when: primary_manager == inventory_hostname
  - name: Join Additional Docker Swarm Managers To Cluster
    command: >
      docker swarm join
      --advertise-addr {{ansible_default_ipv4.address}}
      --token {{ hostvars[primary_manager]['manager_token'] }}
      {{ hostvars[primary_manager]['ansible_default_ipv4']['address'] }}
    when: >
      primary_manager != inventory_hostname and
      "Swarm: active" not in docker_info.stdout and
      "Swarm: pending" not in docker_info.stdout
