---
  - name: Join Docker Swarm Workers To Cluster
    command: >
      docker swarm join
      --advertise-addr {{ansible_default_ipv4.address}}
      --token {{ hostvars[primary_manager]['worker_token'] }}
      {{ hostvars[primary_manager]['ansible_default_ipv4']['address'] }}
    when: >
      "Swarm: active" not in docker_info.stdout and
      "Swarm: pending" not in docker_info.stdout
