---
  - name: install nfs-utils
    yum:
      name: nfs-utils
      state: latest
  - name: setup perms
    ## something about permissions an config here..
  - name: ensure service enabled and started
    systemd:
      name: nfs-server
      state: started
      enabled: yes
