---
  - name: Configure kubernetes on hosts
    hosts: all
    tags: init
    roles:
      - centos-docker
      - docker-thinpool

# RUN SWAPOFF

  - name: Configure kubernetes on hosts
    hosts: all
    tags: kube
    roles:
      - kube

  - name: Configure kubernetes dashboard on manager
    hosts: managers
    tags: dashboard
    roles:
      - kube-dashboard

# kubectl proxy
# http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
