---
  - name: Ensure coreos hosts have python available
    hosts: coreos
    gather_facts: false
    become: yes
    become_method: sudo
    roles:
      - ansible-coreos
  - name: Configure swarm hosts
    hosts: all
    roles:
      - docker-swarm
