---
  - name: setup kubectl repo
    yum_repository:
      name: Kubernetes
      description: Kubernetes rhel repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey:
        - https://packages.cloud.google.com/yum/doc/yum-key.gpg
        - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - name: install kubectl
    yum:
      name: kubectl
      state: present
