---
  - name: ensure .docker directory
    file:
      dest: $HOME/.docker
      state: directory
  - name: copy docker credentials
    copy:
      src: config.json
      dest: $HOME/.docker/config.json
