- name: Setup Workers
  include: workers.yml
  when: inventory_hostname in groups.workers
  tags: init

- name: Setup Manager in parts
  when: inventory_hostname in groups.managers
  block:
    - include: storage.yml
      tags: init
    - include: bootstrap.yml
      tags: init

      # WAIT FOR BOOTSTRAP TO COMPLETE
    - include: connections-env.yml
      tags: env

    # WAIT FOR HELM INIT
    - include: cp-infrastructure.yml
      tags: infra

    # WAIT FOR ALL PODS TO PULL AND START
    - include: orient-me.yml
      tags: orient

    # WAIT FOR ALL PODS TO PULL AND START
    - include: cnx-ingress.yml
      tags: ingress

    # WAIT FOR ALL PODS TO PULL AND START
    - include: sanity.yml
      tags: sanity
