---
  - name: Install easy_install
    yum:
      name: python-setuptools
      state: present
  - name: install pip
    easy_install:
      name: pip
      state: present
  - name: install docker-compose
    pip:
      name: docker-compose
  - name: setup /docker directory
    file:
      path: /docker
      state: directory
