all:

  # Add common user credentials here
  vars:
    ansible_user: nicky
    ansible_ssh_private_key_file: /home/nicky/.ssh/google_compute_engine
    # must match one of your intended manger hosts
    primary_manager: manager1

  # Define all your hosts here
  hosts:
    manager2:
      ansible_host: 35.211.3.188
    manager1:
      ansible_host: 35.211.143.57
    manager3:
      ansible_host: 35.211.38.65
    demoworker:
      ansible_host: 35.211.223.166

  # Groups
  children:

    # Add any coreos hosts to this group
    # They will get pypy installed at the python_interpreter location below
    # Non coreos nodes will still work but they will be expected to have
    # python and docker installed in a standard manner
    coreos:
      hosts:
        manager1:
        manager2:
        manager3:
        demoworker:
      vars:
        ansible_python_interpreter: /home/core/bin/python

    # Swarm managers group
    managers:
      hosts:
        manager1:
        manager2:
        manager3:

    # Swarm workers group
    # Do not add managers here also
    workers:
      hosts:
        demoworker:
