all:

  # Add common user credentials here
  vars:
    ansible_user: root
    # ansible_ssh_private_key_file: /home/nicky/.ssh/google_compute_engine
    # must match one of your intended manger hosts
    primary_manager: manager1

  # Define all your hosts here
  hosts:
    albinoni:
      ansible_host: 192.168.12.34
    bruckner:
      ansible_host: 192.168.12.35
    caplet:
      ansible_host: 192.168.12.36

  # Groups
  children:
    # kube managers group
    managers:
      hosts:
        bruckner:

    # kube workers group
    workers:
      hosts:
        albinoni:
        caplet:
