---
  - systemd:
      name: docker
      state: stopped

  - command: vgcreate docker /dev/sdb
  - command: lvcreate --wipesignatures y -n thinpool docker -l 95%VG
  - command: lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG
  - command: sudo lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
  - name: create thinpool profile dir
    file:
      dest: /etc/lvm/profile
      state: directory
  - name: create thinpool profile
    copy:
      src: docker-thinpool.profile
      dest: /etc/lvm/profile/docker-thinpool.profile

  - command: lvchange --metadataprofile docker-thinpool docker/thinpool
  - command: lvs -o+seg_monitor

  - name: stat docker
    stat: path=/var/lib/docker
    register: docker_stat

  - name: Move docker to backup
    command: mv /var/lib/docker /var/lib/docker.bk
    when: docker_stat.stat.exists

  - file:
      dest: /var/lib/docker
      state: directory
    when: docker_stat.stat.exists

  - copy:
      src: daemon.json
      dest: /etc/docker/daemon.json

  - systemd:
      name: docker
      state: started

  - command: docker info

  # BREAK FOR SWAPOFF
