---
  - name: Check if bx installed
    command: "/usr/local/bin/bx --version"
    register: bx_output
    ignore_errors: true
    changed_when: false

  - name: Check downloaded bx install
    command: stat $HOME/Bluemix_CLI
    register: bx_file
    changed_when: false

  - name: Download and extract bx
    unarchive:
      src: https://clis.ng.bluemix.net/download/bluemix-cli/latest/linux64
      dest: $HOME
      remote_src: yes
    when: bx_output is failed and bx_file is failed

  - name: Register home dir
    command: pwd
    register: user_home
    args:
      chdir: $HOME
    changed_when: false

  - name: Install IBM Cloud CLI
    command: ./install_bluemix_cli
    args:
      chdir: "{{ user_home.stdout }}/Bluemix_CLI"
    when: bx_output is failed
    become: true
    become_user: root

  - name: Ensure bx is up to date
    command: /usr/local/bin/bx update
    when: bx_output is success
    register: bx_update
    changed_when: "'No update required' not in bx_update.stdout"

  - name: Check if container-service installed
    command: "/usr/local/bin/bx cs help"
    register: bx_cs_output
    ignore_errors: true
    changed_when: false

  - name: Install container-service plugin
    command: /usr/local/bin/bx plugin install container-service
    when: bx_cs_output is failed

  - name: Ensure container-service is up to date
    command: /usr/local/bin/bx plugin update container-service
    when: bx_cs_output is success
    register: bx_cs_update
    changed_when: "'No updates are available' not in bx_cs_update.stdout"
