- name: Setup Mongo nfs
  tags: storage, mongo
  block:
    - file:
        path: /pv-kudos/mongo
        state: directory
        mode: 0777
    - lineinfile:
        dest: /etc/exports
        line: "/pv-kudos/mongo 192.168.0.0/255.255.0.0(rw,no_root_squash)"
        state: present

- name: Setup Minio nfs
  tags: storage, minio
  block:
    - file:
        path: /pv-kudos/minio
        state: directory
        mode: 0777
    - lineinfile:
        dest: /etc/exports
        line: "/pv-kudos/minio 192.168.0.0/255.255.0.0(rw,no_root_squash)"
        state: present

- name: Apply new NFS storage to exports"
  tags: storage, mongo, minio
  command: exportfs -ra

- name: Install Mongo
  tags: storage, mongo
  block:
    - copy:
        src: mongo.yaml
        dest: /root/install/mongo.yaml
    - command: kubectl apply -f /root/install/mongo.yaml

- name: Install Minio
  tags: storage, minio
  block:
    - copy:
        src: minio.yaml
        dest: /root/install/minio.yaml
    - command: kubectl apply -f /root/install/minio.yaml
